# Generated by Django 2.2.4 on 2019-09-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
