# Generated by Django 3.0.1 on 2020-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date_time',
            field=models.CharField(default='02-01-2020 16:29:07', max_length=200),
        ),
    ]
