# Generated by Django 3.0.1 on 2020-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_auto_20200102_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date_time',
            field=models.CharField(default='02-01-2020 10:24:02', max_length=200),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(default='memories_photo/default.jpg', upload_to='memories_photo'),
        ),
    ]
