# Generated by Django 3.0.1 on 2020-01-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0012_auto_20200102_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date_time',
            field=models.CharField(default='02-01-2020 21:22:12', max_length=200),
        ),
    ]
