# Generated by Django 3.0.1 on 2020-01-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0013_auto_20200102_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date_time',
            field=models.CharField(default='02-01-2020 22:42:06', max_length=200),
        ),
    ]
